### ISSUE TITLE
Pass Options for Each Notification

### ISSUE THREAD

**Issue by joelhickok** [rakk7/vue-bootstrap-toasts#2]
Just found your project!  Nice work, I like it and am using it.

*An idea:*

Accept an options object per Toast, so that you can override the timeout for each message.  If I find time to work on it soon, I'll submit a pull request, but not sure if that will happen right away for me.

```
this.$toast.success('This is your message', {
    timeOut: 0, // stays open
    closeable: true,
});
```
```
this.$toast.warning('You will be logged out in 10 seconds!', {
    timeOut: 10000
});
```

**Comment by rakk7** [comment]
Thank you for the feedback,
added in v1.0.5
